version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=/api # Настроено для работы через Nginx
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - 80:80

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - 8000:8000

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: {{sensitive_data}}
      POSTGRES_PASSWORD: {{sensitive_data}}
      POSTGRES_DB: {{sensitive_data}}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
